# Generated by Django 2.2 on 2020-06-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_firstname', models.CharField(default='', max_length=20)),
                ('customer_lastname', models.CharField(default='', max_length=20)),
                ('customer_username', models.CharField(default='', max_length=20)),
                ('customer_contact', models.CharField(default='', max_length=20)),
                ('customer_email', models.CharField(default='', max_length=50)),
                ('customer_address', models.CharField(default='', max_length=100)),
                ('customer_city', models.CharField(default='', max_length=20)),
                ('customer_state', models.CharField(default='', max_length=20)),
                ('customer_zip', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=30)),
                ('product_image', models.ImageField(upload_to='shop/images')),
                ('product_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_firstname', models.CharField(default='', max_length=20)),
                ('vendor_lastname', models.CharField(default='', max_length=20)),
                ('vendor_username', models.CharField(default='', max_length=20)),
                ('vendor_contact', models.CharField(default='', max_length=20)),
                ('vendor_email', models.CharField(default='', max_length=50)),
                ('vendor_address', models.CharField(default='', max_length=100)),
                ('vendor_city', models.CharField(default='', max_length=20)),
                ('vendor_state', models.CharField(default='', max_length=20)),
                ('vendor_zip', models.CharField(default='', max_length=10)),
                ('apple', models.IntegerField(default='')),
                ('banana', models.IntegerField(default='')),
                ('cabbage', models.IntegerField(default='')),
                ('capsicum', models.IntegerField(default='')),
                ('cauliflower', models.IntegerField(default='')),
                ('chilly', models.IntegerField(default='')),
                ('coriander', models.IntegerField(default='')),
                ('garlic', models.IntegerField(default='')),
                ('ginger', models.IntegerField(default='')),
                ('grapes', models.IntegerField(default='')),
                ('guava', models.IntegerField(default='')),
                ('jackfruit', models.IntegerField(default='')),
                ('lemon', models.IntegerField(default='')),
                ('lychee', models.IntegerField(default='')),
                ('mango', models.IntegerField(default='')),
                ('mushroom', models.IntegerField(default='')),
                ('onion', models.IntegerField(default='')),
                ('orange', models.IntegerField(default='')),
                ('papaya', models.IntegerField(default='')),
                ('pear', models.IntegerField(default='')),
                ('pea', models.IntegerField(default='')),
                ('pineapple', models.IntegerField(default='')),
                ('pomegranate', models.IntegerField(default='')),
                ('potato', models.IntegerField(default='')),
                ('pumpkin', models.IntegerField(default='')),
                ('scallion', models.IntegerField(default='')),
                ('spinach', models.IntegerField(default='')),
                ('tomato', models.IntegerField(default='')),
                ('turnip', models.IntegerField(default='')),
                ('watermelon', models.IntegerField(default='')),
                ('broccoli', models.IntegerField(default='')),
                ('carrot', models.IntegerField(default='')),
                ('cucumber', models.IntegerField(default='')),
            ],
        ),
    ]
